#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".json"

META_DIR="meta"
CONFIG_DIR="configs"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

git -C "${BASE_DIR}" submodule update --init --remote

for config in "$@"; do
    configFile="$(mktemp)"

    jq -s add "${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}" "${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}" >"$configFile"
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "$BASE_DIR" -c "$configFile"

    rm -f "$configFile"
done
