### Added by Zplugin's installer
source ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

autoload -Uz zargs zmv zcp zln

source ~/.zsh/variables.zsh

# Prompt
source ~/.zsh/powerlevel10k-settings.zsh
zplugin light romkatv/powerlevel10k

# Oh-my-zsh libs
zplugin snippet OMZ::lib/history.zsh

zplugin snippet OMZ::lib/directories.zsh

zplugin snippet OMZ::lib/key-bindings.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/git.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/completion.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/grep.zsh

# Oh-my-zsh plugins
zplugin ice wait"0" lucid atload"unalias grv"
zplugin snippet OMZ::plugins/git/git.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/systemd/systemd.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/sudo/sudo.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/extract/extract.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/archlinux/archlinux.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/command-not-found/command-not-found.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/systemadmin/systemadmin.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/golang/golang.plugin.zsh
# Plugins
zplugin ice wait"0" lucid atinit"zpcompinit; zpcdreplay"
zplugin light zdharma/fast-syntax-highlighting

zplugin ice wait"0" blockf lucid
zplugin light clarketm/zsh-completions

zplugin ice wait"0" lucid atload"_zsh_autosuggest_start"
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" lucid
zplugin light zdharma/history-search-multi-word

zplugin ice wait"0" lucid
zplugin light MichaelAquilina/zsh-you-should-use

source ~/.zsh/aliases.zsh
