#!/usr/bin/env sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

[ -f /etc/xprofile ] && . /etc/xprofile
# shellcheck source=./xprofile
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

if [ "$(supergfxctl -g)" = 'dedicated' ]; then
	xrandr --setprovideroutputsource modesetting NVIDIA-G0
	xrandr --auto
fi

exec i3
