### Added by Zplugin's installer
source ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk

ZSH_AUTOSUGGEST_USE_ASYNC="true"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=50

# Prompt
zplugin light denysdovhan/spaceship-prompt

# Oh-my-zsh libs
zplugin snippet OMZ::lib/history.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/git.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/key-bindings.zsh

zplugin ice wait"0" lucid atload"unalias grv"
zplugin snippet OMZ::plugins/git/git.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/completion.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::lib/grep.zsh

# Oh-my-zsh plugins
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/systemd/systemd.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/sudo/sudo.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/extract/extract.plugin.zsh

# Plugins
zplugin ice wait"0" lucid atinit"zpcompinit"
zplugin light zdharma/fast-syntax-highlighting

zplugin ice wait"0" blockf lucid
zplugin light zsh-users/zsh-completions

zplugin ice wait"0" lucid atload"_zsh_autosuggest_start"
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" lucid
zplugin light zdharma/history-search-multi-word

zplugin ice wait"0" lucid
zplugin light djui/alias-tips


SPACESHIP_PROMPT_ORDER=(
time          # Time stamps section
user          # Username section
dir           # Current directory section
host          # Hostname section
git           # Git section (git_branch + git_status)
# hg          # Mercurial section (hg_branch  + hg_status)
package       # Package version
node          # Node.js section
# ruby        # Ruby section
# elm         # Elm section
# elixir      # Elixir section
# xcode       # Xcode section
# swift       # Swift section
golang        # Go section
# php         # PHP section
# rust        # Rust section
# haskell     # Haskell Stack section
# julia       # Julia section
# docker      # Docker section
# aws         # Amazon Web Services section
venv          # virtualenv section
# conda       # conda virtualenv section
pyenv         # Pyenv section
# dotnet      # .NET section
# ember       # Ember.js section
# kubecontext # Kubectl context section
# terraform   # Terraform workspace section
exec_time     # Execution time
line_sep      # Line break
battery       # Battery level and status
# vi_mode     # Vi-mode indicator
jobs          # Background jobs indicator
exit_code     # Exit code section
char          # Prompt character
)


if (( $+commands[lsd] )); then
	alias ls="lsd"
	alias l="ls -la"
	alias la="ls -a"
	alias ll="ls -l"
else
	alias l="ls -lah"
	alias la="ls -A"
	alias ll="ls -lh"
fi

alias -- -='cd -'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias md='mkdir -p'
alias rd=rmdir

alias dotfiles="cd ~/.dotfiles"

if (( $+commands[nvim] )); then
	alias v="nvim"
	alias vconf="v ~/.config/nvim/init.vim"
	export EDITOR='nvim'
fi

alias update-mirrorlist="sudo reflector --verbose -c 'GE' -c 'NL' -c 'UA' --age 6 -p http --sort rate --save /etc/pacman.d/mirrorlist"
alias h=htop
alias mpv-tw="mpv --profile=twitch"

alias q="exit"


export GOPATH=$HOME/go
